version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: darius4441
      POSTGRES_PASSWORD: veryStrongPassword
      POSTGRES_DB: refill_db
    ports:
      - "54333:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - 63799:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
